import { useState } from "react";
import { Ico } from "../../components/icons/Icons.jsx";
import StatusChip from "../../components/ui/StatusChip.jsx";
import DrilldownModal from "../../components/ui/DrilldownModal.jsx";

const ICON_COLORS = {
  dollar: "#5b8de0",
  bolt: "#f59e0b",
  gauge: "#14b8a6",
  leaf: "#16a34a",
  factory: "#8b5cf6",
};

/* Parse numeric from strings like "16.2%", "$163M", "91/100", "Ready" */
function parseKpiNum(val) {
  if (typeof val === "number") return val;
  const s = String(val);
  if (s === "Ready") return 90;
  if (s === "Conditional") return 55;
  if (s === "Not Ready") return 20;
  const m = s.match(/[\d.]+/);
  return m ? parseFloat(m[0]) : 0;
}

function buildDrillContent(k, color) {
  const n = parseKpiNum(k.value);
  const id = k.id;
  const icon = k.icon;

  if (id === "roi") {
    return {
      title: "Site ROI",
      subtitle: `${k.value} return on infrastructure investment`,
      icon,
      description:
        "Return on investment for site infrastructure capital deployed. Calculated as net annual operational value created (savings + revenue uplift) divided by total committed capital. A higher rate indicates efficient capital deployment and strong operational performance.",
      threshold: {
        current: n,
        max: 25,
        unit: "% ROI",
        bands: [
          { label: "Poor (<8%)", max: 8, color: "#dc2626" },
          { label: "Acceptable (8–12%)", max: 12, color: "#d97706" },
          { label: "Strong (12%+)", max: 25, color: "#16a34a" },
        ],
      },
      sparkData: [n - 3, n - 2.5, n - 2, n - 1.8, n - 1.5, n - 1.2, n - 1, n - 0.8, n - 0.5, n - 0.3, n - 0.1, n],
      trendPct: k.trend,
      trendPos: k.trendPos,
      trendCaption: k.caption,
      aiRec: `Site ROI of ${k.value} ${n >= 14 ? "is above the enterprise hurdle rate. Continue scaling investment to maximise compound return." : n >= 8 ? "meets minimum threshold. Target 14%+ by optimising utility costs and accelerating occupancy growth." : "is below acceptable threshold — operational restructuring required to restore investment viability."}`,
      contexts: [
        {
          type: n >= 12 ? "success" : "warning",
          heading: "Performance vs Target",
          body: `${k.value} vs enterprise target of 12%. ${n >= 12 ? "Exceeds target — strong capital efficiency." : "Below target — cost reduction and revenue acceleration needed."}`,
        },
        {
          type: "info",
          heading: "Trend",
          body: `ROI ${k.trend} ${k.caption}. Trajectory driven by operational savings and capital deployment efficiency.`,
        },
      ],
    };
  }

  if (id === "invest") {
    return {
      title: "Site Investment",
      subtitle: `${k.value} committed capital`,
      icon,
      description:
        "Total committed infrastructure capital for this site across power, water, transport, digital, and civil works programmes. Reflects total approved budget including spend-to-date and contracted future obligations. Indicates the scale of infrastructure buildout and strategic priority ranking within the portfolio.",
      threshold: {
        current: n,
        max: 250,
        unit: "$M",
        bands: [
          { label: "Underfunded (<$50M)", max: 50, color: "#dc2626" },
          { label: "Developing ($50–$100M)", max: 100, color: "#d97706" },
          { label: "Well-funded ($100M+)", max: 250, color: "#16a34a" },
        ],
      },
      sparkData: [n * 0.6, n * 0.65, n * 0.7, n * 0.75, n * 0.78, n * 0.82, n * 0.85, n * 0.88, n * 0.92, n * 0.95, n * 0.98, n].map((v) =>
        Math.round(v),
      ),
      trendPct: k.trend,
      trendPos: k.trendPos,
      trendCaption: k.caption,
      aiRec: `Capital commitment of ${k.value} ${n >= 120 ? "indicates this is a high-priority site. Ensure spending velocity aligns with construction milestones to avoid carry cost drag." : "is adequate for current programme scope. Review whether incremental capital reallocation from lower-ROI sites is warranted."}`,
      contexts: [
        {
          type: n >= 100 ? "success" : "info",
          heading: "Capital Status",
          body: `${k.value} committed — ${n >= 120 ? "anchor site investment level" : "standard portfolio allocation"}. ${k.trend} vs previous period.`,
        },
        {
          type: "info",
          heading: "Category Split",
          body: "Typical allocation: Power & Utilities 40%, Civil & Foundation 30%, Logistics 20%, Digital 10%.",
        },
      ],
    };
  }

  if (id === "savings") {
    return {
      title: "Operational Savings",
      subtitle: `${k.value} annualised savings`,
      icon,
      description:
        "Annualised operational savings generated by infrastructure efficiency improvements, renewable energy deployment, logistics optimisation, and predictive maintenance programmes. Represents cash flow benefit directly attributable to capital investment at this site.",
      threshold: {
        current: n,
        max: 60,
        unit: "$M/yr",
        bands: [
          { label: "Low (<$10M)", max: 10, color: "#dc2626" },
          { label: "Moderate ($10–$20M)", max: 20, color: "#d97706" },
          { label: "Strong ($20M+)", max: 60, color: "#16a34a" },
        ],
      },
      sparkData: [n * 0.5, n * 0.55, n * 0.62, n * 0.68, n * 0.72, n * 0.76, n * 0.8, n * 0.84, n * 0.88, n * 0.92, n * 0.96, n].map(
        (v) => Math.round(v * 10) / 10,
      ),
      trendPct: k.trend,
      trendPos: k.trendPos,
      trendCaption: k.caption,
      aiRec: `Operational savings of ${k.value} ${n >= 25 ? "demonstrate strong capital efficiency. Extend predictive maintenance AI to remaining units to target $35M+ annual savings." : n >= 10 ? "are growing. Renewable tariff conversion and automated logistics will add $8–12M to annual run rate within 24 months." : "are below target. Conduct comprehensive operational efficiency audit to identify the highest-impact saving opportunities."}`,
      contexts: [
        {
          type: n >= 20 ? "success" : "info",
          heading: "Savings Drivers",
          body: "Primary saving categories: energy tariff optimisation, predictive maintenance, logistics route efficiency, and water recycling.",
        },
        { type: "info", heading: "Trend", body: `Savings ${k.trend} annualised. ${k.caption}.` },
      ],
    };
  }

  if (id === "esg") {
    return {
      title: "ESG Score",
      subtitle: `${k.value} — Industry Benchmark: 71`,
      icon,
      description:
        "Enterprise sustainability composite score across carbon, water, renewable energy, waste reduction, and community impact dimensions. Benchmarked against the Pacific Northwest industrial sector average of 71. Scores above 80 unlock access to green bond financing and preferential regulatory treatment.",
      threshold: {
        current: n,
        max: 100,
        unit: "/ 100",
        bands: [
          { label: "Below Benchmark (<65)", max: 65, color: "#dc2626" },
          { label: "Benchmark (65–80)", max: 80, color: "#d97706" },
          { label: "Leader (80+)", max: 100, color: "#16a34a" },
        ],
      },
      sparkData: [n - 7, n - 6, n - 5, n - 4.5, n - 4, n - 3.5, n - 3, n - 2.5, n - 2, n - 1.5, n - 0.5, n].map((v) => Math.round(v)),
      trendPct: k.trend,
      trendPos: k.trendPos,
      trendCaption: k.caption,
      aiRec: `ESG score of ${k.value} ${n >= 85 ? "is well above industry benchmark of 71. To reach 90+ (green bond threshold), focus on Scope 3 supply chain emissions and water reuse targets." : n >= 65 ? "meets benchmark. Water reuse improvement and renewable energy procurement are the two highest-leverage actions to reach 85+." : "is below industry benchmark — urgent sustainability programme required. Start with renewable energy tariff and water recycling investment."}`,
      contexts: [
        {
          type: n >= 80 ? "success" : n >= 65 ? "warning" : "danger",
          heading: "Benchmark Position",
          body: `${k.value} vs industry average of 71. ${n >= 80 ? "Leader position — above benchmark by ${n - 71} points." : `Below or near benchmark — ${71 - n > 0 ? `${71 - n} points below` : "at benchmark level"}.`}`,
        },
        {
          type: "info",
          heading: "Key Drivers",
          body: "ESG driven by carbon intensity, renewable share, water reuse rate, and community impact metrics.",
        },
      ],
    };
  }

  if (id === "expansion") {
    const readyNum = parseKpiNum(k.value);
    return {
      title: "Expansion Readiness",
      subtitle: `${k.value} — ${k.caption}`,
      icon,
      description:
        "AI-assessed readiness of the site for next-phase manufacturing expansion. Combines infrastructure capacity headroom, permit status, utility availability, construction lead time, and financial viability into a single go/no-go determination. A 'Ready' status means expansion can commence within 12 months.",
      threshold: {
        current: readyNum,
        max: 100,
        unit: "Score",
        bands: [
          { label: "Not Ready (<40)", max: 40, color: "#dc2626" },
          { label: "Conditional (40–75)", max: 75, color: "#d97706" },
          { label: "Ready (75+)", max: 100, color: "#16a34a" },
        ],
      },
      sparkData: [
        readyNum - 15,
        readyNum - 12,
        readyNum - 10,
        readyNum - 8,
        readyNum - 7,
        readyNum - 6,
        readyNum - 5,
        readyNum - 4,
        readyNum - 3,
        readyNum - 2,
        readyNum - 1,
        readyNum,
      ].map((v) => Math.max(0, v)),
      trendPct: k.trend,
      trendPos: k.trendPos,
      trendCaption: k.caption,
      aiRec: `Expansion readiness is ${k.value}. ${k.value === "Ready" ? "All infrastructure prerequisites confirmed. Proceed to Phase 2 detailed engineering and contractor procurement to maintain preferred build slot." : "Conditional status — resolve identified infrastructure gaps (power and utility upgrades) before committing expansion capital."}`,
      contexts: [
        {
          type: k.value === "Ready" ? "success" : "warning",
          heading: "Readiness Status",
          body: `${k.value} — ${k.caption}. ${k.value === "Ready" ? "AI confidence score confirms all systems go for Phase 2 expansion." : "Power or infrastructure upgrade required before expansion commitment."}`,
        },
        {
          type: "info",
          heading: "Timeline",
          body:
            k.value === "Ready"
              ? "Phase 2 construction can commence within 60 days. Estimated completion: 18–24 months."
              : "Estimated time to Ready status: 12–18 months pending infrastructure upgrades.",
        },
      ],
    };
  }

  return { title: k.label, subtitle: k.value, icon, description: k.caption, threshold: null, sparkData: null, aiRec: "", contexts: [] };
}

/* ── Executive KPI drilldown content (score / capex / land / permitting / construction) ── */
function buildExecDrillContent(k) {
  const n = parseKpiNum(k.value);
  const id = k.id;
  const icon = k.icon;

  if (id === "score") {
    return {
      title: "Overall Site Score",
      subtitle: `${k.value} — Multi-Criteria Site Analysis`,
      icon,
      description:
        "AI-computed composite site score across 47 parameters including infrastructure capacity, environmental compliance, logistics connectivity, regulatory clarity, and financial viability. A score above 85 indicates a site ready for immediate capital commitment. Updated quarterly as new engineering survey data becomes available.",
      threshold: {
        current: n,
        max: 100,
        unit: "/ 100",
        bands: [
          { label: "Review Required (<70)", max: 70, color: "#dc2626" },
          { label: "Good (70–85)", max: 85, color: "#d97706" },
          { label: "Excellent (85+)", max: 100, color: "#16a34a" },
        ],
      },
      sparkData: Array.from({ length: 12 }, (_, i) => Math.round(Math.max(60, n - (11 - i) * 0.8))),
      trendPct: k.trend,
      trendPos: k.trendPos,
      trendCaption: k.caption,
      aiRec: `Site score of ${k.value} ${n >= 90 ? "places this site in the top tier of the acquisition portfolio. Proceed to Phase 1 detailed engineering and pre-application permit conference." : n >= 80 ? "indicates a strong candidate. Target 90+ by addressing the top infrastructure gap in the environmental assessment." : "is conditional. Prioritise the infrastructure investment plan to reach 85+ before capital commitment."}`,
      contexts: [
        {
          type: n >= 85 ? "success" : n >= 70 ? "warning" : "danger",
          heading: "Score Assessment",
          body: `${k.value} — ${n >= 90 ? "Top-ranked in portfolio. All primary criteria met." : n >= 80 ? "Strong performer. Minor gaps in 2–3 sub-criteria identified." : "Conditional. Infrastructure investment required before commitment."}`,
        },
        {
          type: "info",
          heading: "Methodology",
          body: "Score aggregates 47 parameters: Power 35%, Water 20%, Logistics 20%, ESG 15%, Solar 10%. Updated quarterly from engineering survey data.",
        },
      ],
    };
  }

  if (id === "capex") {
    const capexM = parseFloat(String(k.value).replace(/[$M]/g, "")) || n;
    return {
      title: "CAPEX Estimate",
      subtitle: `${k.value} — Pre-Development Capital Estimate`,
      icon,
      description:
        "Pre-development capital expenditure estimate covering site preparation, utilities infrastructure, buildings, and major equipment. Derived from Class 5 cost estimating methodology. Confidence rating reflects survey data completeness and market pricing maturity. Final CAPEX will be refined at each stage gate.",
      threshold: {
        current: Math.min(capexM, 1000),
        max: 1000,
        unit: "$M",
        bands: [
          { label: "Light (<$250M)", max: 250, color: "#16a34a" },
          { label: "Mid-Scale ($250–$600M)", max: 600, color: "#d97706" },
          { label: "Major (>$600M)", max: 1000, color: "#5b8de0" },
        ],
      },
      sparkData: Array.from({ length: 12 }, (_, i) => Math.round(capexM * (0.72 + (i / 11) * 0.28))),
      trendPct: k.trend,
      trendPos: k.trendPos,
      trendCaption: k.caption,
      aiRec: `CAPEX of ${k.value} with ${k.trend.replace("+", "")} confidence. ${capexM >= 600 ? "Large-scale programme — stage-gate approach recommended. Secure major utility contracts early to avoid escalation. Establish 12–15% contingency reserve." : capexM >= 250 ? "Mid-scale investment. Phased drawdown aligned with construction milestones. Key risk: material price escalation — consider early procurement of structural steel and electrical equipment." : "Efficient capital programme. Focus on utility pre-work in Year 1 to unlock full site readiness within 18 months."}`,
      contexts: [
        {
          type: k.trendPos ? "success" : "warning",
          heading: "Estimate Confidence",
          body: `${k.trend.replace("+", "")} confidence rating. Estimate class: Pre-development (±30%). Next milestone: design development estimate (±15%) at detailed engineering completion.`,
        },
        {
          type: "info",
          heading: "Cost Breakdown",
          body: "Typical allocation: Site prep & civil 25%, Utilities & infrastructure 30%, Buildings & structure 30%, Equipment & fit-out 15%. Excludes land acquisition.",
        },
      ],
    };
  }

  if (id === "land") {
    const landM = parseFloat(String(k.value).replace(/[$M]/g, "")) || n;
    return {
      title: "Land Acquisition Cost",
      subtitle: `${k.value} — Real Estate Appraisal`,
      icon,
      description:
        "Estimated land acquisition cost based on commercial real estate appraisal, comparable sales analysis, and assessed value. Includes all parcels within the study area boundary. Subject to negotiation, environmental contingencies, and title clearance. Expressed as a percentage of total CAPEX for portfolio benchmarking.",
      threshold: {
        current: Math.min(landM, 200),
        max: 200,
        unit: "$M",
        bands: [
          { label: "Low (<$40M)", max: 40, color: "#16a34a" },
          { label: "Moderate ($40–$100M)", max: 100, color: "#d97706" },
          { label: "High (>$100M)", max: 200, color: "#dc2626" },
        ],
      },
      sparkData: Array.from({ length: 12 }, (_, i) => Math.round(landM * (0.88 + (i / 11) * 0.12))),
      trendPct: k.trend,
      trendPos: k.trendPos,
      trendCaption: k.caption,
      aiRec: `Land cost of ${k.value} (${k.trend}) is ${landM <= 50 ? "competitive for the location and site size. Early LOI submission recommended to lock pricing ahead of market appreciation." : landM <= 100 ? "moderate for the region. Negotiate a purchase option with 12-month exclusivity to allow permitting progress before full commitment." : "at the high end — verify appraisal basis and explore phasing a portion of the site to reduce initial land capital commitment."}`,
      contexts: [
        {
          type: landM <= 60 ? "success" : landM <= 100 ? "warning" : "danger",
          heading: "Appraisal Basis",
          body: `${k.value} based on commercial real estate appraisal and comparable industrial land transactions. ${k.trend} of total CAPEX.`,
        },
        {
          type: "info",
          heading: "Acquisition Strategy",
          body: "Recommended: conditional purchase agreement tied to permit milestone, exclusivity period of 12 months, environmental contingency clause for Phase II ESA findings.",
        },
      ],
    };
  }

  if (id === "permitting") {
    return {
      title: "Permitting Timeline",
      subtitle: `${k.value} — Regulatory Assessment`,
      icon,
      description:
        "Estimated time from permit application submission to full construction permit issuance, covering environmental review (SEPA), building permits, NPDES stormwater permit, utility easements, and FAA/airspace coordination. Timeline reflects the complexity of the local regulatory environment and multi-agency review requirements.",
      threshold: {
        current: n,
        max: 36,
        unit: "months",
        bands: [
          { label: "Fast-track (<18 mo)", max: 18, color: "#16a34a" },
          { label: "Standard (18–22 mo)", max: 22, color: "#d97706" },
          { label: "Complex (22+ mo)", max: 36, color: "#dc2626" },
        ],
      },
      sparkData: Array.from({ length: 12 }, (_, i) => Math.max(12, Math.round(n - 4 + (i / 11) * 4))),
      trendPct: k.trend,
      trendPos: k.trendPos,
      trendCaption: k.caption,
      aiRec: `Permitting timeline of ${k.value} ${n <= 18 ? "is fast-track — confirms straightforward regulatory pathway. File complete permit package immediately to maintain construction start schedule." : n <= 22 ? "is within standard range. Pre-application conference with county planning recommended to identify any issues early." : "indicates a complex multi-agency review environment. Engage a specialist permitting consultant and begin pre-application coordination at least 6 months before planned filing."}`,
      contexts: [
        {
          type: n <= 18 ? "success" : n <= 22 ? "warning" : "danger",
          heading: "Regulatory Environment",
          body: `${k.trend} permitting pathway. Key agencies: county planning, EPA (NPDES), and utility easement approvals. SEPA environmental review ${n <= 18 ? "straightforward" : "may require extended review"}.`,
        },
        {
          type: "info",
          heading: "Critical Path",
          body: "Longest lead-time item: SEPA environmental checklist and NPDES stormwater permit. Begin permit preparation 3 months before planned application submission date.",
        },
      ],
    };
  }

  if (id === "construction") {
    return {
      title: "Construction Timeline",
      subtitle: `${k.value} — Project Schedule`,
      icon,
      description:
        "Estimated construction duration from groundbreaking to certificate of occupancy, based on project scope, site size, and comparable industrial construction programmes. Includes civil works, utilities infrastructure, and primary building construction. Excludes fit-out and commissioning phases (typically 6–12 months additional).",
      threshold: {
        current: n,
        max: 72,
        unit: "months",
        bands: [
          { label: "Accelerated (<36 mo)", max: 36, color: "#16a34a" },
          { label: "Standard (36–48 mo)", max: 48, color: "#d97706" },
          { label: "Extended (48+ mo)", max: 72, color: "#dc2626" },
        ],
      },
      sparkData: Array.from({ length: 12 }, (_, i) => Math.max(28, Math.round(n - 4 + (i / 11) * 4))),
      trendPct: k.trend,
      trendPos: k.trendPos,
      trendCaption: k.caption,
      aiRec: `Construction timeline of ${k.value} ${n <= 36 ? "is accelerated — achievable with early contractor procurement and pre-ordered long-lead items. Add 6 months for commissioning and validation before manufacturing start." : n <= 48 ? "is standard for this project scope. Establish a fast-track procurement package for structural steel and electrical equipment to protect the schedule. Monthly programme reviews recommended." : "is extended — review scope for opportunities to phase construction and enable earlier partial occupancy. Modular construction for auxiliary buildings can save 6–8 months."}`,
      contexts: [
        {
          type: n <= 36 ? "success" : n <= 48 ? "warning" : "danger",
          heading: "Schedule Assessment",
          body: `${k.value} construction period. Top schedule risks: long-lead electrical equipment (22–28 week lead time), concrete supply availability, and weather delays.`,
        },
        {
          type: "info",
          heading: "Schedule Risk",
          body: "Build 10% schedule contingency into programme. Consider modular construction for non-critical auxiliary buildings to accelerate overall site readiness.",
        },
      ],
    };
  }

  return { title: k.label, subtitle: k.value, icon, description: k.caption, threshold: null, sparkData: null, aiRec: "", contexts: [] };
}

export default function ExecKPIs({ kpis }) {
  const [drilldown, setDrilldown] = useState(null);

  return (
    <>
      <div className="kpi-grid-5">
        {kpis.map((k) => {
          const color = ICON_COLORS[k.icon] || "#5b8de0";
          const ragColor = k.rag === "success" ? "#16a34a" : k.rag === "warning" ? "#d97706" : k.rag === "danger" ? "#dc2626" : color;
          return (
            <div
              key={k.id}
              className="stat-mini-card"
              style={{ borderTop: `2px solid ${ragColor}`, cursor: "pointer" }}
              onClick={() => setDrilldown(k)}
              tabIndex={0}
              onKeyDown={(e) => e.key === "Enter" && setDrilldown(k)}
              role="button"
              aria-label={`${k.label}: ${k.value}. Click for details.`}
            >
              <div style={{ display: "flex", alignItems: "center", gap: 6, marginBottom: 6 }}>
                <div
                  style={{
                    width: 26,
                    height: 26,
                    borderRadius: 8,
                    background: ragColor,
                    display: "flex",
                    alignItems: "center",
                    justifyContent: "center",
                    color: "#fff",
                  }}
                >
                  <Ico name={k.icon} size={13} />
                </div>
                <span className="stat-mini-card__label" style={{ fontSize: 9 }}>
                  {k.label}
                </span>
              </div>
              <span className="stat-mini-card__value" style={{ color: ragColor, fontSize: 19 }}>
                {k.value}
              </span>
              <span className={`stat-mini-card__trend ${k.trendPos ? "pos" : "neg"}`}>{k.trend}</span>
              <span className="stat-mini-card__sub">{k.caption}</span>
            </div>
          );
        })}
      </div>
      {drilldown && (
        <DrilldownModal
          kpi={{
            icon: drilldown.icon,
            status: drilldown.rag?.toUpperCase(),
            ragStatus: drilldown.rag,
            value: drilldown.value,
            trendPct: drilldown.trend,
            trendPos: drilldown.trendPos,
            trendCaption: drilldown.caption,
            sparkData: (["score", "capex", "land", "permitting", "construction"].includes(drilldown.id)
              ? buildExecDrillContent(drilldown)
              : buildDrillContent(drilldown, null)
            ).sparkData,
          }}
          directContent={
            ["score", "capex", "land", "permitting", "construction"].includes(drilldown.id)
              ? buildExecDrillContent(drilldown)
              : buildDrillContent(drilldown, null)
          }
          onClose={() => setDrilldown(null)}
        />
      )}
    </>
  );
}
